### ISSUE TITLE
Allow for mutation of base collection

### ISSUE THREAD

**Issue by OlegKleyman** [romantitov/MockQueryable#23]
Currently when mutating the base collection such that:

```csharp
var userEntities = new List<UserEntity>();
var set = userEntities.AsQueryable().BuildMockDbSet()
userEntities.Add(new UserEntity());
set.Single();
```
results in the following exception:

> System.InvalidOperationException : Collection was modified; enumeration operation may not execute.

It would be good to allow for mutation of the base enumerable when possible.

>

**Comment by romantitov** [comment]
the functionality available in ver. 3.0.2
