### ISSUE TITLE
DotNet5.0 Compatibility

### ISSUE THREAD

**Issue by ibwStef** [romantitov/MockQueryable#35]
Tried upgrading to .net5.0 preview6 .

I get the following error: System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

After Installing Microsoft.Bcl.AsyncInterfaces from Nuget I get:
System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by romantitov** [comment]
Hello @ibwStef, thank you for your feedback. I'm planning to add support .Net 5 after official release.

**Comment by romantitov** [comment]
@ibwStef I've made packages v5.0.0-preview.7  for new version of .Net 5 https://www.nuget.org/packages/MockQueryable.Moq/5.0.0-preview.7.
 Also there is a special brunch https://github.com/romantitov/MockQueryable/tree/Dotnet5.0
For current moment this is all what can I do.

**Comment by ibwStef** [comment]
@romantitov Thank you, that is totally fine.
