### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by mcollera** [romantitov/MockQueryable#36]
Is it possible to get this package created with a strong name?

**Comment by romantitov** [comment]
Hello @mcollera, thanks for your feedback. May I know in which scenarios packages with strong names required for you?

**Comment by mcollera** [comment]
Yes. Currently we are trying to reference MovkQueryable.Moq but since our code requires a strong name we are unable to reference

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by romantitov** [comment]
Did you try to use [strongnamer](https://github.com/dsplaisted/strongnamer)?

**Comment by romantitov** [comment]
I'm closing the issue because workaround has been provided
