### ISSUE TITLE
Support for .NET 5 ?

### ISSUE THREAD

**Issue by rathga** [romantitov/MockQueryable#37]
Any current plans to yet?

Trying the FakeItEasy flavour it in a .NET 5 RC2 project and seems to fail with: 

```
System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

... which I install, but then it fails with:
```
Result Message:	System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

Which I'm guessing might be a namespace difference between core 3.1 and 5 ?

code is `var fakeQueryable = new List<Enquiry>().AsQueryable().BuildMock();`

**Comment by romantitov** [comment]
@rathga  thank you for your feedback. 
Similar issue #35  was already created and closed. Could you try to use [preview version for FakeItEasy](https://www.nuget.org/packages/MockQueryable.FakeItEasy/5.0.0-preview.7). 
If you still facing the issue let me know, I'll create a new package for RC2

**Comment by rathga** [comment]
The existing preview version works well!  Thank you

Sorry, I did not think to look for it on nuget or to search the closed issues
