### ISSUE TITLE
RE: IQueryable mock throws on ToListAsync()

### ISSUE THREAD

**Issue by sstream17** [romantitov/MockQueryable#38]
This issue is related to #32 but there was no resolution given there so I am opening a new issue.

When mocking an IQueryable, I am getting the exception
```
System.InvalidOperationException : The source IQueryable doesn't implement IAsyncEnumerable<Event>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.
```

My code is structured as follows:
```
// Method Under Test
public async Task<List<Event>> GetEvents(FilterOptions filterOptions)
{
	var queryable = GetEventsQueryable();

	queryable = FilterByDate(queryable, filterOptions);
	// queryable = FilterByLocation(), FilterBy...(), etc

	var events = await queryable
		.ToListAsync()
		.ConfigureAwait(false);

	return events;
}

public IQueryable<Event> GetEventQueryable()
{
	try
	{
		return MyDbContext
			.EventData
			.AsQueryable();
	}
	catch
	{
		...
	}
}

public IQueryable<Event> FilterByDate(
	IQueryable<Event> queryable,
	FilterOptions options)
{
	if (options.StartDate != null)
	{
		queryable = queryable.Where(e => e.EventDate >= options.StartDate);
	}

	if (options.EndDate != null)
	{
		queryable = queryable = queryable.Where(e => e.EventDate <= options.EndDate);
	}

	return queryable;
}

// Test
private List<Event> Events
{
	get
	{
		new List<Event>
		{
			...
		};
	}
}

[Fact]
public void GetEvents_DefaultFilterOptions_ReturnsAllEvents()
{
	// Arrange
	var mockQueryable = Events.AsQueryable().BuildMock();

	var expectedEvents = new List<Event>
	{
		...
	};
	
	...
	mockCaller
		.Setup(m => m.GetEventsQueryable())
		.Returns(mockQueryable);

	mockCaller
		.Setup(m => m.FilterByDate(It.IsAny<IQueryable<Event>>(), It.IsAny<FilterOptions>()))
		.Returns(mockQueryable);

	var eventManager = new EventManager();

	var filterOptions = new EventFilterOptions();

	// Act
	var actualEvents = eventManager.GetEvents(filterOptions);

	// Assert
	Assert.Equal(expectedEvents, actualEvents);
}
```

When the test gets to the `events = await queryable.ToListAsync()` line it throws the System.InvalidOperationException.

I am not sure what is going wrong or how to fix the issue. I started looking into using the TestAsyncEnumerableEfCore<Event> class and trying to return this instead of the mocked queryable, but the issue still persisted.

**Comment by romantitov** [comment]
@sstream17 Thank you for your feedback. Do the methods  GetEvents, GetEventQueryable and FilterByDate located in the same class?

**Comment by sstream17** [comment]
No, all three methods are in their own classes and separate csproj. I will create a small example and post the repository link here when it is ready.

**Comment by sstream17** [comment]
@romantitov I have created a [repository with an example of the error](https://github.com/sstream17/MQ38).

**Comment by romantitov** [comment]
@sstream17 if you change your test like this it will work.
![image](https://user-images.githubusercontent.com/11888679/98017854-21c00e00-1e00-11eb-9b63-26c2d84e4397.png)

**Comment by sstream17** [comment]
Thank you! I think I accidentally copied from an older commit, which is why the `BuildMock()` call was missing. You are correct, the real issue was the missing nullable DateTimes in the mock. Can't believe it was so simple. Thanks for your help.
