### ISSUE TITLE
Unit Tests Of Methods Using EF.Functions Broken By EFCore 5

### ISSUE THREAD

**Issue by matttamatic** [romantitov/MockQueryable#43]
In https://github.com/dotnet/efcore/issues/20294 the client side implementations of EF.Functions methods (eg EF.Functions.Like) were removed which broke any unit tests using them with mockqueryable data.

**Comment by matttamatic** [comment]
I'm looking into trying to fix this by borrowing the client side implementations they deleted, but it might be beyond me

**Comment by matttamatic** [comment]
Not worth the effort, better off using inmemoryprovider for any tests that require EF extensions.

**Comment by matttamatic** [comment]
I think this is a mess, but if anybody wants it, this branch demonstrates a working unit test using EF.Like 
https://github.com/matttamatic/MockQueryable/tree/InMemEFLike
All the extra code is taken from various classes in EFCore 5

**Comment by hasmikharutyunyan** [comment]
@matttamatic  I have the same problem, why  have You closed the issue?

**Comment by matttamatic** [comment]
Because it was vastly easier to rewrite my broken tests using an InMemoryDatabase and every time upstream EF Core made any changes to the InMemory versions of EF.Functions, it would have to be manually pulled again.  
(Basically, just that it was a unmaintainable mess)
