### ISSUE TITLE
System.InvalidOperationException in Empty mock.

### ISSUE THREAD

**Issue by anilsnl** [romantitov/MockQueryable#44]
Hi,

When I try to use BuildMock().Object with an empty list, I've got the following exception. In my case, I use ToListAsync() method of EF Core. 

`System.InvalidOperationException: The source 'IQueryable' doesn't implement 'IAsyncEnumerable<Kazandirio.CampaignRepository.Model.Campaign>'. Only sou...`

`  _campaignUnitOfWorkMock.Setup(a => a.GetQueryable<Campaign>())
                .Returns(() => new List<Campaign>().AsQueryable().BuildMock().Object);`

**Comment by romantitov** [comment]
Hi @anilsnl, thanks you for the issue.
I would really like to help you but unfortunately I cannot reproduce the issue, following test with empty list works fine:
```
    [TestCase("01/20/2010", "02/20/2011", 0)]
    public async Task GetUserReports(DateTime from, DateTime to, int expectedCount)
    {
      //arrange
      var userRepository = new Mock<IUserRepository>();
      var service = new MyService(userRepository.Object);
      var users = new List<UserEntity>
      {

      };
      //expect
      var mock = users.AsQueryable().BuildMock();
      userRepository.Setup(x => x.GetQueryable()).Returns(mock.Object);
      //act
      var result = await service.GetUserReports(from, to);
      //assert
      Assert.AreEqual(expectedCount, result.Count);
     }
``` 
Could you provide full code of your test?

**Comment by anilsnl** [comment]
Thanks for your help & feedback.

 I made some mistakes in the namespaces of my model so it throws the exception. Now it fixed. I'm closing the issue.
