### ISSUE TITLE
Composite Primary Key

### ISSUE THREAD

**Issue by ChrTall** [romantitov/MockQueryable#46]
Hi, is there a way to have a dbSetMock with a composite primary key?

**Comment by romantitov** [comment]
Hello @ChrTall, thank you for your feedback.
Could you provide code example for the issue please?

**Comment by ChrTall** [comment]
I tested a bit and my problem is not related to a composite primary key.

I have the following Setup:```

var persons = new List<Person>()
{
     new Person()
       {
          Id = 1, Name = "Chris"
       }
}
var dbSetMock = persons.AsQueryable().BuildMockDbSet();
var context = appDbContextFactory.CreateInMemoryDbContext();
context.Persons = dbSetMock.Object;
```

I can use context to get All Persons or the Person with the Id=1. 
But when I try to add or update the Person and call context.SaveChanges().
The DbSet Persons is not updated. Maybe this is out of scope for your service and I am using it in a way that is not supported.

**Comment by romantitov** [comment]
@ChrTall   execution of methods such `SaveChanges` is a bit out of scope of the  library. But built mock object can be extended. In your case you can setup additional logic for SaveChanges in your tests. You can find an example [here](https://github.com/romantitov/MockQueryable/issues/7)
