### ISSUE TITLE
Can I use AddAsync and expect to have the result in the mocked DbSet?

### ISSUE THREAD

**Issue by norcino** [romantitov/MockQueryable#47]
Hi I use this library and now I have encountered an issue, in one of my tests I need to trigger a class that behind the scene uses AddAsync to add the item I am passing in, then using the same context.dbset I am trying to get it but the dbset does not contain the element, only preexisting objects.
Is this scenario not supported?

Thank you

**Comment by romantitov** [comment]
Hi @norcino, thank you for the feedback.  
MockQueryable provides you an approach to test asynchronous Queryable operations, but you can also extend the mock object with additional operations. You can find an example in #7  .
