### ISSUE TITLE
Write Entities 

### ISSUE THREAD

**Issue by cfindlayvcs** [romantitov/MockQueryable#51]

**Comment by cfindlayvcs** [comment]
I have mock db sets working. It's great.

But, when `AddOrAttach` is called, I would hope that the record is added to the list so that I can assert the added record. That would be awesome.

**Comment by romantitov** [comment]
Hi @cfindlayvcs , thank you for your feedback. If I understood you correctly you want to add some custom logic to the mock db set. If so, the mock object generated by MockQueryable is very flexible and you can add implementation for `AddOrAttach` by yourself, you can find an example in #7. 
If the solution doesn't help you, please reopen the issue.
