### ISSUE TITLE
Set return value of FirstOrDefaultAsync method by NSubstitute returns error

### ISSUE THREAD

**Issue by Ramin-Bateni** [romantitov/MockQueryable#53]
When I want to set a return value (null or none-null value) for `FindOrDefaultAsync` method I get the following error:
```Can not return value of type Task`1 for IQueryable.get_Expression (expected type Expression).```

```
[Fact]
public async Task FindRole_WhenCall_ReturnsIdentityRole()
{
    // Arrange
    var iRole = new IdentityRole();
    var dbset = new List<IdentityRole>()
    {
        new IdentityRole()
    }
    .AsQueryable().BuildMockDbSet();
    
    dbset.FirstOrDefaultAsync(role => role.Name=="a")
        .ReturnsNull();

    _repository.Query().Returns(dbset);
    
    // Act
    var result = await _rolesService.FindRole("RoleName");

    // Assert
    result.Should().BeNull();
}
```
![image](https://user-images.githubusercontent.com/9051320/140739431-81c0bd06-9551-4bcb-af0a-223ca75757bf.png)

**Comment by romantitov** [comment]
@Ramin-Bateni  it doesn't seems to be an issue of MockQueryable. Looks like you override logic for FirstOrDefaultAsync. 
[Here](https://github.com/romantitov/MockQueryable/blob/master/src/MockQueryable/MockQueryable.Sample/MyServiceNSubstituteTests.cs) you can find the test `CreateUserIfNotExist` which also covers FirstOrDefaultAsync inside of `service.CreateUserIfNotExist`. I hope it will help you to update your test.

**Comment by romantitov** [comment]
Closing the issue since there is no changes for MockQueryable require
