### ISSUE TITLE
ToListAsync() returns empty list after package update to 6.0.0

### ISSUE THREAD

**Issue by VILLAN3LL3** [romantitov/MockQueryable#58]
After having updated the MockQueryable package to version 6.0.0 some of my unit tests fail because `.ToListAsync()` now returns an empty list.
Example code:

```
DbSet<Sections> mockSections = sections.AsQueryable().BuildMockDbSet();
_dbContext.Sections.Returns(mockSections); 
List<Section> sections = await _dbContext.Sections.ToListAsync(cancellationToken); 
```

The last line returns an empty list with the new package version. Why?

The failed tests and the full test code can be found [here](https://github.com/orso-co/Orso.Arpa.Api/runs/5702849918?check_suite_focus=true)

**Comment by romantitov** [comment]
Thank you @VILLAN3LL3 for your feedback. The issue fixed in the release [v6.0.1](https://github.com/romantitov/MockQueryable/releases/tag/v6.0.1).

**Comment by NanoWar** [comment]
With version 6.0.1 I'm running a similar issue as mentioned in #23 . When I change the base collection after using ToListAsync on the mock, I also get `System.InvalidOperationException : Collection was modified; enumeration operation may not execute.`

**Comment by romantitov** [comment]
Hello @NanoWar. Thank you for your feedback. Could you create a new issue for that and add an example of unit tests to reproduce the your issue.
