### ISSUE TITLE
Return value of SaveChangesAsync

### ISSUE THREAD

**Issue by gerwintmg** [romantitov/MockQueryable#65]
In my test i use
```csharp
mockContext.Verify(_ => _.SaveChangesAsync(), Times.Once());
```
to verify that SaveChangesAsync() is called

in the function i test. I check if the SaveChanges call is successful by its result
```csharp
int results = await _context.SaveChangesAsync(CancellationToken.None);
if (results >= 1)
{
	return new OkObjectResult();
} 
return new BadRequestObjectResult();

```

While testing my function fails as SaveChangesAsync always returns 0;

I'm i doing something wrong? or is This a Bug?

**Comment by romantitov** [comment]
Hello @gerwintmg . Thanks for the issue. 
You can add setup for SaveChangesAsync by yourself. See #7 as an example.
