### ISSUE TITLE
Move BuildMock to MockQueryable.EntityFrameworkCore

### ISSUE THREAD

**Issue by skarllot** [romantitov/MockQueryable#77]
Move the extension method `BuildMock` to the package `MockQueryable.EntityFrameworkCore`.

**Comment by romantitov** [comment]
Hello @skarllot  could you provide more detailed reason why this change should be done?

**Comment by skarllot** [comment]
Because it does not depend on `NSubstitute` but only on the `TestAsyncEnumerableEfCore` class defined in `MockQueryable.EntityFrameworkCore`, it would allow sharing the implementation regardless of the mocking library used, and furthermore, allow using no mocking library at all if the user desires.

**Comment by romantitov** [comment]
Done in v7.0.2

**Comment by scp-mb** [comment]
Breaking change on a patch version? Not cool. Why not release is at 8.0.0 if it's got a breaking change in it.
