### ISSUE TITLE
AutoMapper .ProjectTo fix

### ISSUE THREAD

**Issue by seandevenish** [romantitov/MockQueryable#9]
AutoMapper casts an IQueryable to IQueryable<T> which breaks the current implementation of CreateQuery in the TestAsyncEnumerable class. I have got this working by adding the following into the public IQueryable CreateQuery(Expression expression) method:

```            
public IQueryable CreateQuery(Expression expression)
{    
    if (expression is MethodCallExpression m)
    {
        var resultType = m.Method.ReturnType; // it shoud be IQueryable<T>
        var tElement = resultType.GetGenericArguments()[0];
        var queryType = typeof(TestAsyncEnumerable<>).MakeGenericType(tElement);
        return (IQueryable)Activator.CreateInstance(queryType, expression);
    }
    return new TestAsyncEnumerable<T>(expression);
}
```

**Comment by romantitov** [comment]
Could you create pull request for the fix, and add the case to [MockQueryable.Sample](https://github.com/romantitov/MockQueryable/tree/master/src/MockQueryable/MockQueryable.Sample)? We will be glad to include the fix to the next release

**Comment by romantitov** [comment]
AutoMapper supported from ver 1.0.4
